pub const DEFAULT_VSYNC: bool = false;
pub const DEFAULT_MAX_FPS: u16 = 0;
pub const DEFAULT_WINDOWED: bool = true;
pub const DEFAULT_DISPLAY_MONITOR: usize = 0;
pub const DEFAULT_LOG_TO_FILE: bool = true;
pub const DEFAULT_SHOW_CONSOLE: bool = false;
pub const DEFAULT_WRITE_CURRENT_SCREEN: bool = false;
pub const DEFAULT_TAB_ACCELERATION: bool = true;
pub const DEFAULT_SHOW_STATS_MODE: u8 = 0;
pub const DEFAULT_TRANSLATED_TITLES: bool = false;
pub const DEFAULT_MINE_HIT_SOUND: bool = true;
pub const DEFAULT_BG_BRIGHTNESS: f32 = 0.7;
pub const DEFAULT_CENTER_1PLAYER_NOTEFIELD: bool = false;
pub const DEFAULT_BANNER_CACHE: bool = true;
pub const DEFAULT_CDTITLE_CACHE: bool = true;
pub const DEFAULT_DISPLAY_WIDTH: u32 = 1600;
pub const DEFAULT_DISPLAY_HEIGHT: u32 = 900;
pub const DEFAULT_CENTER_IMAGE_TRANSLATE_X: i32 = 0;
pub const DEFAULT_CENTER_IMAGE_TRANSLATE_Y: i32 = 0;
pub const DEFAULT_CENTER_IMAGE_ADD_WIDTH: i32 = 0;
pub const DEFAULT_CENTER_IMAGE_ADD_HEIGHT: i32 = 0;
pub const DEFAULT_HIGH_DPI: bool = false;
pub const DEFAULT_HIDE_MOUSE_CURSOR: bool = true;
pub const DEFAULT_GFX_DEBUG: bool = false;
pub const DEFAULT_ALLOW_SHUTDOWN_HOST: bool = false;
pub const DEFAULT_SMX_INPUT: bool = false;
pub const DEFAULT_SMX_MANAGES_PAD_CONFIG: bool = false;
pub const DEFAULT_SMX_PANEL_LIGHTS: bool = false;
pub const DEFAULT_SMX_UNDERGLOW_THEME: bool = false;
pub const DEFAULT_SMX_UNDERGLOW_GRB: bool = false;
pub const DEFAULT_SMX_IDLE_LIGHTS_BLACK: bool = false;
pub const DEFAULT_SMX_DEFAULT_LIGHT_BRIGHTNESS: u8 = 100;
pub const DEFAULT_SOFTWARE_RENDERER_THREADS: u8 = 1;
pub const DEFAULT_SONG_PARSING_THREADS: u8 = 0;
pub const DEFAULT_SIMPLY_LOVE_COLOR: i32 = 2;
pub const DEFAULT_SHOW_SELECT_MUSIC_GAMEPLAY_TIMER: bool = true;
pub const DEFAULT_SHOW_SELECT_MUSIC_STAGE_DISPLAY: bool = true;
pub const DEFAULT_SHOW_SELECT_MUSIC_BANNERS: bool = true;
pub const DEFAULT_SHOW_SELECT_MUSIC_VIDEO_BANNERS: bool = true;
pub const DEFAULT_SHOW_SELECT_MUSIC_BREAKDOWN: bool = true;
pub const DEFAULT_SHOW_SELECT_MUSIC_CDTITLES: bool = true;
pub const DEFAULT_SHOW_MUSIC_WHEEL_GRADES: bool = true;
pub const DEFAULT_SHOW_MUSIC_WHEEL_LAMPS: bool = true;
pub const DEFAULT_SORT_MUSIC_WHEEL_BY_SERIES: bool = true;
pub const DEFAULT_HIDE_INACTIVE_SERIES: bool = false;
pub const DEFAULT_SHOW_SELECT_MUSIC_FOLDER_STATS: bool = false;
pub const DEFAULT_SHOW_SELECT_MUSIC_PREVIEWS: bool = true;
pub const DEFAULT_SHOW_SELECT_MUSIC_PREVIEW_MARKER: bool = false;
pub const DEFAULT_SELECT_MUSIC_PREVIEW_LOOP: bool = true;
pub const DEFAULT_SELECT_MUSIC_PREVIEW_STARTS_IMMEDIATELY: bool = true;
pub const DEFAULT_KEYBOARD_FEATURES: bool = true;
pub const DEFAULT_SHOW_VERSION_OVERLAY: bool = true;
pub const DEFAULT_SHOW_VIDEO_BACKGROUNDS: bool = true;
pub const DEFAULT_MACHINE_SHOW_SELECT_PROFILE: bool = true;
pub const DEFAULT_ALLOW_SWITCH_PROFILE_IN_MENU: bool = false;
pub const DEFAULT_MACHINE_SHOW_SELECT_COLOR: bool = true;
pub const DEFAULT_MACHINE_SHOW_SELECT_STYLE: bool = true;
pub const DEFAULT_MACHINE_SHOW_SELECT_PLAY_MODE: bool = true;
pub const DEFAULT_DELAYED_BACK: bool = true;
pub const DEFAULT_MACHINE_ENABLE_REPLAYS: bool = true;
pub const DEFAULT_MACHINE_ENABLE_HEART_RATE_MONITORS: bool = false;
pub const DEFAULT_MACHINE_ALLOW_PER_PLAYER_GLOBAL_OFFSETS: bool = false;
pub const DEFAULT_MACHINE_PACK_INI_OFFSETS: bool = false;
pub const DEFAULT_MACHINE_SHOW_EVAL_SUMMARY: bool = true;
pub const DEFAULT_MACHINE_NICE_SOUND: bool = false;
pub const DEFAULT_MACHINE_SHOW_NAME_ENTRY: bool = true;
pub const DEFAULT_MACHINE_SHOW_GAMEOVER: bool = true;
pub const DEFAULT_ZMOD_RATING_BOX_TEXT: bool = false;
pub const DEFAULT_SHOW_BPM_DECIMAL: bool = false;
pub const DEFAULT_NULL_OR_DIE_CONFIDENCE_PERCENT: u8 = 80;
pub const DEFAULT_NULL_OR_DIE_PACK_SYNC_THREADS: u8 = 0;
pub const DEFAULT_NULL_OR_DIE_FINGERPRINT_MS: f64 = 50.0;
pub const DEFAULT_NULL_OR_DIE_WINDOW_MS: f64 = 10.0;
pub const DEFAULT_NULL_OR_DIE_STEP_MS: f64 = 0.2;
pub const DEFAULT_NULL_OR_DIE_MAGIC_OFFSET_MS: f64 = 0.0;
pub const DEFAULT_NULL_OR_DIE_FULL_SPECTROGRAM: bool = false;
pub const DEFAULT_SHOW_SELECT_MUSIC_SCOREBOX: bool = true;
pub const DEFAULT_SELECT_MUSIC_SCOREBOX_CYCLE_ITG: bool = true;
pub const DEFAULT_SELECT_MUSIC_SCOREBOX_CYCLE_EX: bool = true;
pub const DEFAULT_SELECT_MUSIC_SCOREBOX_CYCLE_HARD_EX: bool = true;
pub const DEFAULT_SELECT_MUSIC_SCOREBOX_CYCLE_TOURNAMENTS: bool = true;
pub const DEFAULT_SELECT_MUSIC_CHART_INFO_PEAK_NPS: bool = true;
pub const DEFAULT_SELECT_MUSIC_CHART_INFO_EFFECTIVE_BPM: bool = false;
pub const DEFAULT_SELECT_MUSIC_CHART_INFO_MATRIX_RATING: bool = false;
pub const DEFAULT_SHOW_RANDOM_COURSES: bool = true;
pub const DEFAULT_SHOW_MOST_PLAYED_COURSES: bool = true;
pub const DEFAULT_SHOW_COURSE_INDIVIDUAL_SCORES: bool = true;
pub const DEFAULT_AUTOSUBMIT_COURSE_SCORES_INDIVIDUALLY: bool = true;
pub const DEFAULT_GLOBAL_OFFSET_SECONDS: f32 = -0.008;
pub const DEFAULT_VISUAL_DELAY_SECONDS: f32 = 0.0;
pub const DEFAULT_MASTER_VOLUME: u8 = 90;
pub const DEFAULT_MENU_MUSIC: bool = true;
pub const DEFAULT_CUSTOM_SOUNDS_ENABLED: bool = true;
pub const DEFAULT_MUSIC_VOLUME: u8 = 100;
pub const DEFAULT_MUSIC_WHEEL_SWITCH_SPEED: u8 = 15;
pub const DEFAULT_ASSIST_TICK_VOLUME: u8 = 100;
pub const DEFAULT_SFX_VOLUME: u8 = 100;
pub const DEFAULT_AUTO_DOWNLOAD_UNLOCKS: bool = false;
pub const DEFAULT_AUTO_POPULATE_GS_SCORES: bool = false;
pub const DEFAULT_UPDATER_INSTALL_ENABLED: bool = true;
pub const DEFAULT_RATE_MOD_PRESERVES_PITCH: bool = true;
pub const DEFAULT_ENABLE_REPLAYGAIN: bool = false;
pub const DEFAULT_ENABLE_ARROWCLOUD: bool = false;
pub const DEFAULT_ENABLE_BOOGIESTATS: bool = false;
pub const DEFAULT_ENABLE_GROOVESTATS: bool = false;
pub const DEFAULT_SHOW_SRPG_SHOP: bool = true;
pub const DEFAULT_SUBMIT_ARROWCLOUD_FAILS: bool = false;
pub const DEFAULT_SEPARATE_UNLOCKS_BY_PLAYER: bool = false;
pub const DEFAULT_FASTLOAD: bool = true;
pub const DEFAULT_CACHE_SONGS: bool = true;
pub const DEFAULT_ALLOW_SONG_DELETION: bool = false;
pub const DEFAULT_SMOOTH_HISTOGRAM: bool = true;
pub const DEFAULT_SHADE_SCATTERPLOT_JUDGMENTS: bool = false;
pub const DEFAULT_AUTO_SCREENSHOT_EVAL: u8 = 0;
pub const DEFAULT_INPUT_DEBOUNCE_SECONDS: f32 = 0.02;
pub const DEFAULT_ARCADE_OPTIONS_NAVIGATION: bool = false;
pub const DEFAULT_THREE_KEY_NAVIGATION: bool = false;
pub const DEFAULT_USE_FSRS: bool = false;
pub const DEFAULT_LIGHTS_SIMPLIFY_BASS: bool = false;
pub const DEFAULT_ONLY_DEDICATED_MENU_BUTTONS: bool = false;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn core_user_visible_defaults_match_policy() {
        assert!(DEFAULT_CUSTOM_SOUNDS_ENABLED);
        assert!(!DEFAULT_MACHINE_NICE_SOUND);
        assert!(DEFAULT_HIDE_MOUSE_CURSOR);
        assert_eq!(DEFAULT_MUSIC_WHEEL_SWITCH_SPEED, 15);
        assert_eq!(DEFAULT_BG_BRIGHTNESS, 0.7);
        assert!(!DEFAULT_MACHINE_ENABLE_HEART_RATE_MONITORS);
        assert!(!DEFAULT_ALLOW_SONG_DELETION);
    }
}
