[package]
name = "deadsync-audio-stream"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0"

[[bench]]
name = "audio_sample_transforms"
harness = false

[features]
pipewire-audio = ["deadlib-audio/pipewire-audio"]
test-support = []

[dependencies]
deadlib-audio-core = { path = "../deadlib-audio-core" }
deadlib-audio = { path = "../deadlib-audio" }
deadsync-audio-decode = { path = "../deadsync-audio-decode" }
deadsync-audio-replaygain = { path = "../deadsync-audio-replaygain" }
deadlib-platform = { path = "../deadlib-platform" }
log = "0.4.33"
rubato = "5.0.0"
smallvec = "1.15.2"

[lints.clippy]
perf = { level = "warn", priority = -1 }

inline_always = "allow"
