//! `deadsync-screens` — the reloadable hot unit for the menu.
//!
//! This crate compiles the **real** `screens/menu/render.rs` directly into a
//! `cdylib` via `#[path]`, so editing that file and rebuilding only this crate
//! produces a fresh renderer without recompiling the engine rlib. The engine
//! rlib is statically linked for every other type (`State`, `HostContext`,
//! `Actor`, components…). The cdylib exports exactly one symbol,
//! `deadsync_hot_entry`, returning a pointer to a `static HotHeader` whose
//! vtable the host validates and dispatches through (see `deadsync::hot`).
//!
//! Each hot surface is wired by [`hot_local_renders!`]: it maps a
//! `deadsync::hot::HotSurface` marker (which owns the *slot number* in the rlib)
//! to this crate's **local** render fn, generates a typed `LocalRender` impl, and
//! places a generic `thunk::<Surface>` at `Surface::SLOT` in the `static VTABLE`.
//! Because the slot comes from the rlib trait, the cdylib cannot desync slot
//! numbering from the host.
//!
//! NOTE (boundary safety): the render output now crosses as a real
//! **`Vec<Actor>`** by value over the Rust ABI. The `Vec` and every `Arc<str>`
//! it carries are allocated in this cdylib and dropped in the host, so both
//! artifacts MUST be built `-C prefer-dynamic` against one shared `std`/global
//! allocator — otherwise the host frees cdylib heap with a different allocator
//! (UB). The included `render.rs` still mints some `&'static str` font/texture
//! keys that point into *this cdylib's* rodata; such a key only exists within a
//! single render call and must not outlive the loaded generation.
//!
//! SAFETY INVARIANT (no unload while live): a returned `Vec<Actor>` and its
//! `Arc<str>` destructors are this module's code/allocator. The runtime must
//! therefore **never unload a hot generation** while any value it produced is
//! still alive (today it keeps every loaded library mapped for the reloader's
//! lifetime) — running this module's drop glue after unload would be UB.

// The real render path, compiled into THIS crate so edits don't touch the rlib.
// Relative to `crates/deadsync-screens/src/`, the repo root is three levels up.
#[path = "../../../src/screens/menu/render.rs"]
mod render;

use deadsync::engine::present::actors::Actor;
use deadsync::hot::{
    ABI_VERSION, BUILD_HASH, HotEntry, HotHeader, HotSurface, LAYOUT_HASH, MAGIC, MAX_SURFACES,
    MenuSurface, PANIC_STRATEGY, ScreenVTable,
};
use std::panic::{AssertUnwindSafe, catch_unwind};

/// This cdylib's **local** real renderer for a surface. Distinct from
/// [`HotSurface::render`], which is the engine rlib's in-lib *fallback* (the
/// empty stub under `feature = "hot"`). One impl per surface, generated by
/// [`hot_local_renders!`].
trait LocalRender: HotSurface {
    fn local_render(state: &Self::State, ctx: &Self::Context, alpha: f32) -> Vec<Actor>;
}

/// Generic type-erased hot entry: reconstruct the surface's real `&State` /
/// `&Context` from the host's erased pointers, run the cdylib-local renderer
/// under `catch_unwind`, and return the actors by value. One monomorphization
/// per surface; `thunk::<S>` is placed at `S::SLOT` in the vtable. A panic from
/// the (hot-edited) render path is caught here and reported as `None`; no panic
/// crosses the boundary. The returned `Vec<Actor>` (and the `Arc<str>` it
/// carries) is allocated here and dropped in the host — sound only under the
/// shared `-C prefer-dynamic` allocator both artifacts are built with.
///
/// # Safety
/// `state` / `ctx` must point at live `S::State` / `S::Context` values of the
/// layout the host's [`LAYOUT_HASH`] handshake agreed on, valid for the call.
unsafe fn thunk<S: LocalRender>(
    state: *const (),
    ctx: *const (),
    alpha: f32,
) -> Option<Vec<Actor>> {
    catch_unwind(AssertUnwindSafe(|| {
        // SAFETY: under the load-time LAYOUT_HASH / BUILD_HASH handshake these
        // pointers reference live `S::State` / `S::Context` of identical layout in
        // both artifacts; the host holds them valid for this call's duration.
        let state = unsafe { &*(state as *const S::State) };
        let ctx = unsafe { &*(ctx as *const S::Context) };
        S::local_render(state, ctx, alpha)
    }))
    .ok()
}

/// Map each hot surface to its cdylib-local render fn, generating the
/// [`LocalRender`] impls and the `static VTABLE` (each `thunk::<S>` placed at
/// `S::SLOT`, all other slots `None`). The per-surface `let f: fn(&State, …)`
/// binding type-checks the render fn against the surface's associated types, so a
/// mismatched mapping fails to compile rather than casting the wrong layout at
/// runtime.
macro_rules! hot_local_renders {
    ( $( $surface:ty => $render:path ),+ $(,)? ) => {
        $(
            impl LocalRender for $surface {
                fn local_render(
                    state: &<$surface as HotSurface>::State,
                    ctx: &<$surface as HotSurface>::Context,
                    alpha: f32,
                ) -> Vec<Actor> {
                    let f: fn(
                        &<$surface as HotSurface>::State,
                        &<$surface as HotSurface>::Context,
                        f32,
                    ) -> Vec<Actor> = $render;
                    f(state, ctx, alpha)
                }
            }
        )+

        /// The dispatch table this cdylib publishes: a generic `thunk::<S>` at
        /// each surface's `S::SLOT`, every other slot left `None`.
        static VTABLE: ScreenVTable = {
            let mut entries: [Option<HotEntry>; MAX_SURFACES] = [None; MAX_SURFACES];
            $(
                entries[<$surface as HotSurface>::SLOT] = Some(thunk::<$surface> as HotEntry);
            )+
            ScreenVTable { entries }
        };
    };
}

hot_local_renders! {
    MenuSurface => render::get_actors,
}

/// `HotHeader` holds a raw `*const ()` vtable pointer, so it isn't `Sync`. The
/// header is immutable for the life of the dylib and only ever read, so wrapping
/// it to place it in a `static` is sound.
struct HeaderSync(HotHeader);
// SAFETY: `HEADER` is never mutated after construction; the pointer targets the
// `static VTABLE` in this same library, valid for the library's whole lifetime.
unsafe impl Sync for HeaderSync {}

static HEADER: HeaderSync = HeaderSync(HotHeader {
    magic: MAGIC,
    abi_version: ABI_VERSION,
    panic_strategy: PANIC_STRATEGY,
    _pad: [0; 3],
    size: size_of::<HotHeader>() as u32,
    layout_hash: LAYOUT_HASH,
    build_hash: BUILD_HASH,
    vtable: &VTABLE as *const ScreenVTable as *const (),
});

/// The single exported entry point. The host fetches this symbol, reads the
/// header, validates it against `deadsync::hot::EXPECTED`, and dispatches through
/// the vtable on success.
#[unsafe(no_mangle)]
pub extern "C" fn deadsync_hot_entry() -> *const HotHeader {
    &HEADER.0
}
