[package]
name = "deadlib-audio-backend-pipewire"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0"

[target.'cfg(target_os = "linux")'.dependencies]
deadlib-audio-core = { path = "../deadlib-audio-core" }
deadlib-platform = { path = "../deadlib-platform" }
log = "0.4.33"
pipewire = "0.9.2"

[lints.clippy]
perf = { level = "warn", priority = -1 }

inline_always = "allow"
