//! Exact parser parity against fixtures generated by `itgmania-harness-rs`.
//!
//! Run with: `cargo test --test font_itgmania_parity`

use deadlib_assets::{FontStore, parse_font_with_asset_context, parse_sprite_sheet_dims};
use deadlib_present::font::{Glyph, find_glyph, measure_line_width_logical};
use serde::Deserialize;
use std::collections::BTreeSet;
use std::fs;
use std::path::Path;

const FIXTURE_SCHEMA_VERSION: u32 = 1;
const ORACLE_SCHEMA_VERSION: u32 = 1;

#[derive(Deserialize)]
struct Manifest {
    fixture_schema_version: u32,
    oracle_schema_version: u32,
    harness_version: String,
    corpus: String,
    itgmania: Itgmania,
    fonts: Vec<ManifestFont>,
}

#[derive(Deserialize)]
struct Itgmania {
    git_revision: String,
    git_dirty: String,
}

#[derive(Deserialize)]
struct ManifestFont {
    font: String,
    fixture: String,
    glyphs: usize,
}

#[derive(Deserialize)]
struct Fixture {
    schema_version: u32,
    oracle_schema_version: u32,
    font: String,
    corpus: String,
    height: i32,
    line_spacing: i32,
    right_to_left: bool,
    distance_field: bool,
    default_stroke_color: [f32; 4],
    line_width: i32,
    line_height: i32,
    pages: Vec<Page>,
    glyphs: Vec<ExpectedGlyph>,
}

#[derive(Deserialize)]
struct Page {
    texture: String,
    texture_hints: String,
    stroke_texture: Option<String>,
    source_size: Size,
    image_size: Size,
    frames: Size,
    height: i32,
    line_spacing: i32,
    vertical_shift: f32,
    draw_extra_pixels_left: i32,
    draw_extra_pixels_right: i32,
}

#[derive(Deserialize)]
struct Size {
    width: i32,
    height: i32,
}

#[derive(Deserialize)]
struct ExpectedGlyph {
    codepoint: u32,
    uses_default_glyph: bool,
    texture: String,
    frame: u32,
    pen_x: i32,
    advance: i32,
    width: f32,
    height: f32,
    horizontal_shift: f32,
    vertical_shift: f32,
    sample_rect: Rect,
}

#[derive(Deserialize)]
struct Rect {
    left: f32,
    top: f32,
    right: f32,
    bottom: f32,
}

#[test]
fn bundled_fonts_match_itgmania() {
    let project_root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let font_root = project_root.join("assets/fonts");
    let fixture_root = project_root.join("tests/fixtures/itgmania-fonts");
    let manifest: Manifest = read_json(&fixture_root.join("_manifest.json"));

    assert_eq!(manifest.fixture_schema_version, FIXTURE_SCHEMA_VERSION);
    assert_eq!(manifest.oracle_schema_version, ORACLE_SCHEMA_VERSION);
    assert!(!manifest.harness_version.is_empty());
    assert_eq!(manifest.corpus, "all-complete-bmp-plus-default-and-missing");
    assert_eq!(manifest.itgmania.git_revision.len(), 40);
    assert!(matches!(
        manifest.itgmania.git_dirty.as_str(),
        "true" | "false" | "unknown"
    ));

    let expected_fonts = manifest
        .fonts
        .iter()
        .map(|entry| entry.font.clone())
        .collect::<BTreeSet<_>>();
    assert_eq!(expected_fonts, bundled_fonts(&font_root));

    for entry in manifest.fonts {
        let fixture: Fixture = read_json(&fixture_root.join(&entry.fixture));
        assert_eq!(fixture.font, entry.font);
        assert_eq!(fixture.glyphs.len(), entry.glyphs, "{}", entry.font);
        compare_font(&font_root, &fixture);
    }
}

fn compare_font(font_root: &Path, expected: &Fixture) {
    assert_eq!(
        expected.schema_version, FIXTURE_SCHEMA_VERSION,
        "{}",
        expected.font
    );
    assert_eq!(
        expected.oracle_schema_version, ORACLE_SCHEMA_VERSION,
        "{}",
        expected.font
    );
    assert_eq!(
        expected.corpus, "all-complete-bmp-plus-default-and-missing",
        "{}",
        expected.font
    );
    assert!(
        !expected.right_to_left,
        "{} requires right-to-left layout",
        expected.font
    );
    assert!(
        !expected.distance_field,
        "{} requires distance-field rendering",
        expected.font
    );

    let assets_root = font_root
        .parent()
        .expect("font root must be beneath assets");
    let loaded = parse_font_with_asset_context(
        &font_root.join(&expected.font),
        vec![assets_root.to_path_buf()],
    )
    .unwrap_or_else(|error| panic!("could not parse {}: {error}", expected.font));
    let mut store = FontStore::new();
    store.register_font("fixture", loaded.font);
    let fonts = store.fonts();
    let font = fonts.get("fixture").expect("registered fixture font");

    assert_eq!(font.height, expected.height, "{} height", expected.font);
    assert_eq!(
        font.line_spacing, expected.line_spacing,
        "{} line spacing",
        expected.font
    );
    for (index, (&actual, &oracle)) in font
        .default_stroke_color
        .iter()
        .zip(&expected.default_stroke_color)
        .enumerate()
    {
        assert_float(
            oracle,
            actual,
            &expected.font,
            0,
            &format!("stroke[{index}]"),
        );
    }

    compare_pages(font_root, font, expected);
    let text = expected
        .glyphs
        .iter()
        .map(|glyph| {
            char::from_u32(glyph.codepoint)
                .unwrap_or_else(|| panic!("invalid codepoint U+{:04X}", glyph.codepoint))
        })
        .collect::<String>();
    let mut pen_x = 0;
    let mut line_height = 0;
    for oracle in &expected.glyphs {
        let character = char::from_u32(oracle.codepoint)
            .unwrap_or_else(|| panic!("invalid codepoint U+{:04X}", oracle.codepoint));
        let glyph = find_glyph(font, character, fonts).unwrap_or_else(|| {
            panic!(
                "{} has no glyph for U+{:04X}",
                expected.font, oracle.codepoint
            )
        });
        let uses_default = oracle.codepoint == 0xF8FF || !font.glyph_map.contains_key(&character);
        assert_eq!(
            uses_default, oracle.uses_default_glyph,
            "{} U+{:04X} default-glyph selection",
            expected.font, oracle.codepoint
        );
        assert_eq!(
            pen_x, oracle.pen_x,
            "{} U+{:04X} pen",
            expected.font, oracle.codepoint
        );
        compare_glyph(expected, oracle, glyph);
        pen_x += glyph.advance_i32;
        let page = expected
            .pages
            .iter()
            .find(|page| page.texture == oracle.texture)
            .expect("glyph page must be present");
        line_height = line_height.max(page.height);
    }
    assert_eq!(
        measure_line_width_logical(font, &text, fonts),
        expected.line_width,
        "{} line width",
        expected.font
    );
    assert_eq!(pen_x, expected.line_width, "{} final pen", expected.font);
    assert_eq!(
        line_height, expected.line_height,
        "{} line height",
        expected.font
    );
}

fn compare_pages(font_root: &Path, font: &deadlib_present::font::Font, expected: &Fixture) {
    let actual_textures = font
        .glyph_map
        .values()
        .map(|glyph| strip_font_prefix(&glyph.texture_key))
        .collect::<BTreeSet<_>>();
    let expected_textures = expected
        .pages
        .iter()
        .map(|page| page.texture.as_str())
        .collect::<BTreeSet<_>>();
    assert_eq!(
        actual_textures, expected_textures,
        "{} font pages",
        expected.font
    );

    for page in &expected.pages {
        let key = format!("fonts/{}", page.texture);
        let image = image::image_dimensions(font_root.join(&page.texture))
            .unwrap_or_else(|error| panic!("could not inspect {}: {error}", page.texture));
        assert_eq!(
            image.0 as i32, page.image_size.width,
            "{} image width",
            page.texture
        );
        assert_eq!(
            image.1 as i32, page.image_size.height,
            "{} image height",
            page.texture
        );
        let frames = parse_sprite_sheet_dims(&key);
        assert_eq!(
            frames.0 as i32, page.frames.width,
            "{} frame columns",
            page.texture
        );
        assert_eq!(
            frames.1 as i32, page.frames.height,
            "{} frame rows",
            page.texture
        );
        assert!(
            page.source_size.width > 0 && page.source_size.height > 0,
            "{} source size",
            page.texture
        );
        assert!(
            page.height > 0 && page.line_spacing > 0,
            "{} page metrics",
            page.texture
        );
        assert!(
            page.vertical_shift.is_finite(),
            "{} vertical shift",
            page.texture
        );
        assert!(
            page.draw_extra_pixels_left >= 0 && page.draw_extra_pixels_right >= 0,
            "{} extra pixels",
            page.texture
        );
        let hints = font.texture_hints_map.get(&key).map_or("", String::as_str);
        assert_eq!(hints, page.texture_hints, "{} texture hints", page.texture);
        let stroke = font
            .stroke_texture_map
            .get(&key)
            .map(|texture| strip_font_prefix(texture));
        assert_eq!(
            stroke,
            page.stroke_texture.as_deref(),
            "{} stroke texture",
            page.texture
        );
    }
}

fn compare_glyph(expected: &Fixture, oracle: &ExpectedGlyph, actual: &Glyph) {
    let context = format!(
        "{} U+{:04X} frame {}",
        expected.font, oracle.codepoint, oracle.frame
    );
    let codepoint = oracle.codepoint;
    assert_eq!(
        strip_font_prefix(&actual.texture_key),
        oracle.texture,
        "{context} texture"
    );
    assert_eq!(actual.advance_i32, oracle.advance, "{context} advance");
    assert_float(
        oracle.advance as f32,
        actual.advance,
        &context,
        codepoint,
        "float advance",
    );
    assert_float(oracle.width, actual.size[0], &context, codepoint, "width");
    assert_float(oracle.height, actual.size[1], &context, codepoint, "height");
    assert_float(
        oracle.horizontal_shift,
        actual.offset[0],
        &context,
        codepoint,
        "horizontal shift",
    );
    assert_float(
        oracle.vertical_shift,
        actual.offset[1],
        &context,
        codepoint,
        "vertical shift",
    );
    for (label, oracle_value, actual_value) in [
        ("rect left", oracle.sample_rect.left, actual.tex_rect[0]),
        ("rect top", oracle.sample_rect.top, actual.tex_rect[1]),
        ("rect right", oracle.sample_rect.right, actual.tex_rect[2]),
        ("rect bottom", oracle.sample_rect.bottom, actual.tex_rect[3]),
    ] {
        assert_float(oracle_value, actual_value, &context, codepoint, label);
    }
}

fn assert_float(expected: f32, actual: f32, font: &str, codepoint: u32, field: &str) {
    assert_eq!(
        actual.to_bits(),
        expected.to_bits(),
        "{font} U+{codepoint:04X} {field}: expected {expected:?}, actual {actual:?}"
    );
}

fn strip_font_prefix(texture: &str) -> &str {
    texture.strip_prefix("fonts/").unwrap_or(texture)
}

fn bundled_fonts(root: &Path) -> BTreeSet<String> {
    let mut paths = Vec::new();
    collect_ini(root, root, &mut paths);
    paths.into_iter().collect()
}

fn collect_ini(root: &Path, directory: &Path, output: &mut Vec<String>) {
    let entries = fs::read_dir(directory)
        .unwrap_or_else(|error| panic!("could not read {}: {error}", directory.display()));
    for entry in entries {
        let path = entry.expect("font directory entry").path();
        if path.is_dir() {
            collect_ini(root, &path, output);
        } else if path
            .extension()
            .and_then(|extension| extension.to_str())
            .is_some_and(|extension| extension.eq_ignore_ascii_case("ini"))
        {
            output.push(
                path.strip_prefix(root)
                    .expect("font path must remain beneath root")
                    .to_string_lossy()
                    .replace('\\', "/"),
            );
        }
    }
}

fn read_json<T: for<'de> Deserialize<'de>>(path: &Path) -> T {
    let bytes =
        fs::read(path).unwrap_or_else(|error| panic!("could not read {}: {error}", path.display()));
    serde_json::from_slice(&bytes)
        .unwrap_or_else(|error| panic!("invalid fixture {}: {error}", path.display()))
}
