//! Noteskin loader parity against fixtures generated by `itgmania-harness-rs`.
//!
//! Run with: `cargo test --test noteskin_itgmania_parity`

use deadsync_noteskin::itg::{
    clear_data_cache, clear_lookup_caches, discover_skins, load_noteskin_data,
};
use deadsync_noteskin::script::{parse_script_float, parse_script_int};
use serde::Deserialize;
use std::collections::BTreeSet;
use std::fs;
use std::path::{Component, Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

const FIXTURE_SCHEMA_VERSION: u32 = 1;
const ORACLE_SCHEMA_VERSION: u32 = 1;

#[derive(Deserialize)]
struct Manifest {
    fixture_schema_version: u32,
    oracle_schema_version: u32,
    harness_version: String,
    corpus: Corpus,
    itgmania: Itgmania,
    games: Vec<Game>,
    fixtures: Vec<ManifestFixture>,
    source_files: Vec<SourceFile>,
}

#[derive(Deserialize)]
struct Corpus {
    metrics: String,
    paths: String,
    source_snapshot: String,
}

#[derive(Deserialize)]
struct Itgmania {
    git_revision: String,
    git_dirty: String,
}

#[derive(Deserialize)]
struct Game {
    game: String,
    buttons: Vec<String>,
    skins: Vec<String>,
}

#[derive(Deserialize)]
struct ManifestFixture {
    game: String,
    skin: String,
    fixture: String,
    metrics: usize,
    paths: usize,
}

#[derive(Deserialize)]
struct SourceFile {
    path: String,
    bytes: u64,
    text: Option<String>,
}

#[derive(Deserialize)]
struct Fixture {
    schema_version: u32,
    oracle_schema_version: u32,
    game: String,
    skin: String,
    metrics: Vec<Metric>,
    paths: Vec<ResolvedPath>,
}

#[derive(Deserialize)]
struct Metric {
    section: String,
    key: String,
    raw: String,
    integer: i32,
    float: f32,
    boolean: bool,
}

#[derive(Deserialize)]
struct ResolvedPath {
    button: String,
    element: String,
    path: Option<String>,
}

#[test]
fn portable_itgmania_noteskins_match_deadsync_loader() {
    let fixture_root = fixture_root();
    let manifest = read_manifest(&fixture_root);
    let snapshot = Snapshot::create(&manifest.source_files);

    assert_eq!(manifest.fixtures.len(), 28);
    for game in &manifest.games {
        assert!(!game.buttons.is_empty(), "{} button corpus", game.game);
        let expected = game.skins.iter().cloned().collect::<BTreeSet<_>>();
        let actual = discover_skins(&[snapshot.root.clone()], &game.game)
            .into_iter()
            .collect::<BTreeSet<_>>();
        assert_eq!(actual, expected, "{} noteskin inventory", game.game);
    }
    for entry in &manifest.fixtures {
        compare_fixture(&snapshot.root, &fixture_root, entry);
    }
    clear_lookup_caches();
    clear_data_cache();
}

#[test]
fn bundled_deadsync_noteskins_match_itgmania_loader_results() {
    let project_root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let noteskin_root = project_root.join("assets/noteskins");
    let fixture_root = fixture_root();
    let manifest = read_manifest(&fixture_root);
    let installed = manifest
        .fixtures
        .iter()
        .filter(|entry| noteskin_root.join(&entry.game).join(&entry.skin).is_dir())
        .collect::<Vec<_>>();

    assert_eq!(
        installed.len(),
        25,
        "shared bundled noteskin corpus changed"
    );
    for entry in installed {
        compare_fixture(&noteskin_root, &fixture_root, entry);
    }
    clear_lookup_caches();
    clear_data_cache();
}

fn read_manifest(fixture_root: &Path) -> Manifest {
    let manifest: Manifest = read_json(&fixture_root.join("_manifest.json"));
    assert_eq!(manifest.fixture_schema_version, FIXTURE_SCHEMA_VERSION);
    assert_eq!(manifest.oracle_schema_version, ORACLE_SCHEMA_VERSION);
    assert!(!manifest.harness_version.is_empty());
    assert!(manifest.corpus.metrics.contains("every section/key"));
    assert!(manifest.corpus.paths.contains("canonical loader elements"));
    assert!(manifest.corpus.source_snapshot.contains("zero-byte"));
    assert_eq!(manifest.itgmania.git_revision.len(), 40);
    assert!(matches!(
        manifest.itgmania.git_dirty.as_str(),
        "true" | "false" | "unknown"
    ));
    manifest
}

fn compare_fixture(root: &Path, fixture_root: &Path, entry: &ManifestFixture) {
    let expected: Fixture = read_json(&fixture_root.join(&entry.fixture));
    assert_eq!(
        expected.schema_version, FIXTURE_SCHEMA_VERSION,
        "{}",
        entry.fixture
    );
    assert_eq!(
        expected.oracle_schema_version, ORACLE_SCHEMA_VERSION,
        "{}",
        entry.fixture
    );
    assert_eq!(expected.game, entry.game, "{} game", entry.fixture);
    assert_eq!(expected.skin, entry.skin, "{} skin", entry.fixture);
    assert_eq!(
        expected.metrics.len(),
        entry.metrics,
        "{} metrics",
        entry.fixture
    );
    assert_eq!(expected.paths.len(), entry.paths, "{} paths", entry.fixture);

    clear_lookup_caches();
    clear_data_cache();
    let actual = load_noteskin_data(root, &entry.game, &entry.skin)
        .unwrap_or_else(|error| panic!("could not load {}/{}: {error}", entry.game, entry.skin));
    for metric in expected.metrics {
        let raw = actual
            .get_metric(&metric.section, &metric.key)
            .unwrap_or("");
        let context = format!(
            "{}/{} {}::{}",
            entry.game, entry.skin, metric.section, metric.key
        );
        assert_eq!(raw, metric.raw, "{context} raw");
        let number = parse_script_float(raw);
        assert_eq!(parse_script_int(raw), metric.integer, "{context} integer");
        assert_eq!(number.to_bits(), metric.float.to_bits(), "{context} float");
        assert_eq!(
            parse_script_int(raw) != 0,
            metric.boolean,
            "{context} boolean"
        );
    }
    for path in expected.paths {
        let resolved = actual
            .resolve_path(&path.button, &path.element)
            .map(|value| relative_path(root, &value));
        assert_eq!(
            resolved, path.path,
            "{}/{} path {} {}",
            entry.game, entry.skin, path.button, path.element
        );
    }
}

fn relative_path(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or_else(|_| panic!("{} is outside {}", path.display(), root.display()))
        .to_string_lossy()
        .replace('\\', "/")
}

fn fixture_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/itgmania-noteskins")
}

fn read_json<T: for<'de> Deserialize<'de>>(path: &Path) -> T {
    let bytes =
        fs::read(path).unwrap_or_else(|error| panic!("could not read {}: {error}", path.display()));
    serde_json::from_slice(&bytes)
        .unwrap_or_else(|error| panic!("invalid fixture {}: {error}", path.display()))
}

struct Snapshot {
    base: PathBuf,
    root: PathBuf,
}

impl Snapshot {
    fn create(files: &[SourceFile]) -> Self {
        let nonce = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system clock must follow Unix epoch")
            .as_nanos();
        let base = std::env::temp_dir().join(format!(
            "deadsync-itgmania-noteskins-{}-{nonce}",
            std::process::id()
        ));
        let root = base.join("NoteSkins");
        fs::create_dir_all(&root)
            .unwrap_or_else(|error| panic!("could not create {}: {error}", root.display()));
        for source in files {
            let relative = Path::new(&source.path);
            assert!(
                relative
                    .components()
                    .all(|component| matches!(component, Component::Normal(_))),
                "unsafe fixture path {}",
                source.path
            );
            let path = root.join(relative);
            fs::create_dir_all(path.parent().expect("source file must have a parent"))
                .unwrap_or_else(|error| panic!("could not create {}: {error}", path.display()));
            let bytes = source.text.as_deref().unwrap_or("").as_bytes();
            assert!(
                bytes.len() as u64 <= source.bytes,
                "{} source length",
                source.path
            );
            fs::write(&path, bytes)
                .unwrap_or_else(|error| panic!("could not write {}: {error}", path.display()));
        }
        Self { base, root }
    }
}

impl Drop for Snapshot {
    fn drop(&mut self) {
        let temp = std::env::temp_dir();
        assert!(self.base.starts_with(&temp));
        let _ = fs::remove_dir_all(&self.base);
    }
}
