const ROW_IDS: &[RowId] = &[
    RowId::TypeOfSpeedMod,
    RowId::SpeedMod,
    RowId::NoCmodAlternative,
    RowId::Mini,
    RowId::Spacing,
    RowId::Perspective,
    RowId::NoteSkin,
    RowId::SkinArrows,
    RowId::SkinHoldActive,
    RowId::SkinHoldInactive,
    RowId::SkinRollActive,
    RowId::SkinRollInactive,
    RowId::SkinHoldExplosions,
    RowId::SkinMineSize,
    RowId::SkinLifts,
    RowId::MineSkin,
    RowId::ReceptorSkin,
    RowId::TapExplosionSkin,
    RowId::TapExplosionOptions,
    RowId::JudgmentFont,
    RowId::JudgmentColors,
    RowId::JudgmentOffsetX,
    RowId::JudgmentOffsetY,
    RowId::ComboFont,
    RowId::ComboOffsetX,
    RowId::ComboOffsetY,
    RowId::HoldJudgment,
    RowId::HeldGraphic,
    RowId::BackgroundFilter,
    RowId::NoteFieldOffsetX,
    RowId::NoteFieldOffsetY,
    RowId::VisualDelay,
    RowId::GlobalOffsetShift,
    RowId::MusicRate,
    RowId::Stepchart,
    RowId::HeartRateMonitor,
    RowId::MaxHeartRate,
    RowId::WhatComesNext,
    RowId::Exit,
    RowId::Turn,
    RowId::Scroll,
    RowId::Hide,
    RowId::LifeMeterType,
    RowId::LifeBarOptions,
    RowId::DataVisualizations,
    RowId::StepStatsExtra,
    RowId::ScoreDisplay,
    RowId::ScorePosition,
    RowId::DensityGraphBackground,
    RowId::ActionOnMissedTarget,
    RowId::MiniIndicator,
    RowId::IndicatorScoreType,
    RowId::MiniIndicatorSubtractiveDisplay,
    RowId::TargetScore,
    RowId::TargetScorePercent,
    RowId::MiniIndicatorSize,
    RowId::MiniIndicatorColor,
    RowId::MiniIndicatorPosition,
    RowId::GameplayExtras,
    RowId::ColumnFlashJudgments,
    RowId::ColumnFlashBrightness,
    RowId::ColumnFlashSize,
    RowId::LiveTimingStats,
    RowId::CrossoverCues,
    RowId::CrossoverCueBrackets,
    RowId::CrossoverCueQuantization,
    RowId::CrossoverCueDuration,
    RowId::ComboColors,
    RowId::ComboColorMode,
    RowId::CarryCombo,
    RowId::JudgmentTilt,
    RowId::JudgmentTiltIntensity,
    RowId::JudgmentTiltMinThreshold,
    RowId::JudgmentTiltMaxThreshold,
    RowId::JudgmentBehindArrows,
    RowId::OffsetIndicator,
    RowId::ErrorBar,
    RowId::TextErrorBarMode,
    RowId::TextErrorBarThreshold,
    RowId::ShortAverageErrorBar,
    RowId::CenterTick,
    RowId::AverageErrorBarIntensity,
    RowId::AverageErrorBarInterval,
    RowId::ErrorBarTrim,
    RowId::ErrorBarOptions,
    RowId::ErrorBarOffsetX,
    RowId::ErrorBarOffsetY,
    RowId::LongErrorBar,
    RowId::LongErrorBarIntensity,
    RowId::LongErrorBarThreshold,
    RowId::LongErrorBarMinSamples,
    RowId::MeasureCounter,
    RowId::MeasureCounterLookahead,
    RowId::MeasureCounterOptions,
    RowId::MeasureLines,
    RowId::RescoreEarlyHits,
    RowId::EarlyDecentWayOffOptions,
    RowId::ResultsExtras,
    RowId::ScatterplotMaxWindow,
    RowId::TimingWindows,
    RowId::FAPlusOptions,
    RowId::FAPlusWindowOptions,
    RowId::CustomBlueFantasticWindow,
    RowId::CustomBlueFantasticWindowMs,
    RowId::SmxFsrDisplay,
    RowId::SmxPadInputDisplay,
    RowId::SmxBgPack,
    RowId::SmxJudgePack,
    RowId::Insert,
    RowId::Remove,
    RowId::Holds,
    RowId::Accel,
    RowId::Effect,
    RowId::Appearance,
    RowId::Attacks,
    RowId::HideLightType,
    RowId::PadLightBrightness,
    RowId::GameplayExtrasMore,
];

fn visibility(mask: u64) -> RowVisibility {
    RowVisibility {
        show_data_visualizations: mask & (1 << 0) != 0,
        show_measure_counter_children: mask & (1 << 1) != 0,
        show_judgment_offsets: mask & (1 << 2) != 0,
        show_judgment_tilt_options: mask & (1 << 3) != 0,
        show_combo_offsets: mask & (1 << 4) != 0,
        show_error_bar_children: mask & (1 << 5) != 0,
        show_text_error_bar_children: mask & (1 << 6) != 0,
        show_text_error_bar_threshold: mask & (1 << 7) != 0,
        show_average_error_bar_children: mask & (1 << 8) != 0,
        show_long_error_bar_children: mask & (1 << 9) != 0,
        show_custom_fantastic_window_ms: mask & (1 << 10) != 0,
        show_density_graph_background: mask & (1 << 11) != 0,
        show_step_stats_extra: mask & (1 << 12) != 0,
        show_target_score: mask & (1 << 13) != 0,
        show_target_score_percent: mask & (1 << 14) != 0,
        show_early_dw_options: mask & (1 << 15) != 0,
        show_fa_plus_window_options: mask & (1 << 16) != 0,
        show_combo_rows: mask & (1 << 17) != 0,
        show_lifebar_rows: mask & (1 << 18) != 0,
        show_indicator_score_type: mask & (1 << 19) != 0,
        show_mini_indicator_subtractive_display: mask & (1 << 20) != 0,
        show_mini_indicator_size: mask & (1 << 21) != 0,
        show_mini_indicator_color: mask & (1 << 22) != 0,
        show_mini_indicator_position: mask & (1 << 23) != 0,
        show_column_flash_judgments: mask & (1 << 24) != 0,
        show_live_timing_stats: mask & (1 << 25) != 0,
        show_crossover_cue_options: mask & (1 << 26) != 0,
        show_global_offset_shift: mask & (1 << 27) != 0,
        show_tap_explosion_options: mask & (1 << 28) != 0,
        show_pad_light_brightness: mask & (1 << 29) != 0,
        show_smx_fsr_display: mask & (1 << 30) != 0,
        show_smx_pad_input_display: mask & (1 << 31) != 0,
        show_smx_bg_pack: mask & (1 << 32) != 0,
        show_smx_judge_pack: mask & (1 << 33) != 0,
        show_max_heart_rate: mask & (1 << 34) != 0,
    }
}
