pub mod app;

mod command;
mod course;
mod diagnostics;
mod dynamic_media;
mod frame_loop;
mod frame_pacing_trace;
mod frame_stats;
mod frame_stutter;
mod gameplay_entry;
mod gameplay_prewarm;
mod gameplay_runtime;
mod graphics;
mod input;
mod input_backend;
mod input_trace;
mod interaction;
mod lighting;
mod main_menu;
mod navigation;
mod offset_prompt;
mod pad_config;
mod player_options;
mod profile_import;
mod profile_session;
mod restart;
mod runtime;
mod score_import;
mod screen_flow;
mod screenshot;
mod select_music;
mod session;
mod session_results;
mod smx_config;
mod stutter_diag;
mod sync_analysis;
mod transition_effects;
mod window;
mod window_state;

pub(crate) use command::Command;
pub(crate) use course::CourseRunState;
pub(crate) use deadsync_theme::views::FrameStatsSample;
pub(crate) use frame_loop::FrameLoopState;
pub(crate) use frame_pacing_trace::GameplayPacingTrace;
pub(crate) use frame_stats::FrameStatsController;
pub(crate) use input::UserEvent;
pub(crate) use input_trace::GameplayInputTrace;
#[cfg(test)]
pub(crate) use interaction::ExitIntent;
pub(crate) use interaction::ShellInteractionState;
pub(crate) use navigation::{TransitionMusicPaths, TransitionState, transition_audio_plan};
pub(crate) use player_options::player_options_persist_plan;
pub(crate) use runtime::ShellState;
pub(crate) use session::SessionState;
pub(crate) use stutter_diag::StutterDiagRecorder;
