//! Local profile storage and the active-session profile state.
//!
//! Identity model: a profile's canonical id is the `Guid` embedded under
//! `[userprofile]` in its `profile.ini`. The on-disk folder name is cosmetic
//! (derived from the display name) and may change freely. Profiles are resolved
//! by GUID via the `deadsync-profile` runtime directory cache.
//!
//! Cache invariant: any code that creates, deletes, renames, or backfills a
//! profile folder MUST invalidate the runtime directory cache afterwards,
//! because a cache miss is treated as authoritative (no rescan on miss).

pub use crate::app_runtime::{
    active_local_profile_id_for_gameplay_player, append_local_score_for_id,
    cached_ac_chart_hashes_with_itg_for_id, cached_ac_scores_for_id, cached_ac_scores_for_side,
    cached_best_itg_score_for_id, cached_best_itg_score_for_side,
    cached_best_itg_score_with_profile, cached_gs_chart_hashes_for_id, cached_gs_score_for_id,
    cached_gs_score_for_side, cached_itl_score_for_side, cached_itl_score_for_song,
    cached_itl_score_for_song_assume_loaded, cached_itl_score_for_song_with_profile,
    cached_itl_tournament_overall_ranks_for_side, cached_local_ex_score_for_side,
    cached_local_hard_ex_score_for_side, cached_local_itg_score_for_id,
    cached_local_pass_rate_for_id, cached_local_pass_rate_with_profile,
    cached_local_scalar_score_for_side, cached_local_score_for_side,
    cached_online_itl_self_rank_for_key, cached_online_itl_self_rank_for_key_assume_loaded,
    cached_online_itl_self_rank_for_side, cached_online_itl_self_score_for_key,
    cached_online_itl_self_score_for_key_assume_loaded, cached_online_itl_self_score_for_side,
    create_local_profile_from_config as create_local_profile, create_local_profile_from_import,
    default_local_profile_id_for_side_from_config as default_local_profile_id_for_side,
    default_local_profile_options_from_config as default_local_profile_options,
    default_profile_for_side_from_config as get_default_profile_for_side,
    delete_local_profile_from_config as delete_local_profile, delete_pad_config,
    ensure_itl_score_cache_loaded_for_id, ensure_itl_wheel_caches_loaded_for_id,
    ensure_score_caches_loaded_for_id, gameplay_side_for_player, get_arrowcloud_api_key_for_id,
    get_groovestats_api_key_for_id, groovestats_score_service_allowed, import_itl_json,
    import_local_scores_for_id,
    is_groovestats_active_for_side_from_config as is_groovestats_active_for_side,
    itl_song_folder_unlocked_for_side, itl_song_folder_unlocked_with_profile,
    load_default_profiles_for_joined_sides_from_config as load_default_profiles_for_joined_sides,
    load_pad_configs, load_profiles_from_config as load, local_profile_dir_for_id,
    local_score_profile_source_for_id, local_score_profile_sources, machine_default_noteskin,
    machine_leaderboard_local, machine_leaderboard_local_with_names,
    machine_leaderboard_local_without_names, machine_record_local, machine_replays_local,
    mark_known_pack_names_for_local_profile, mark_pack_known, mark_packs_known,
    personal_leaderboard_local_for_side, played_chart_counts_for_id,
    played_chart_counts_for_machine, prewarm_select_music_score_caches, read_itl_file_for_id,
    recent_played_chart_hashes_for_id, recent_played_chart_hashes_for_machine,
    rename_local_profile, rename_pad_config, save_itl_gameplay_players,
    save_local_summary_score_for_side, save_pad_configs, scan_local_profiles,
    score_profile_paths_for_id, scorebox_profile_snapshot_from_config as scorebox_profile_snapshot,
    seed_session_gs_score_for_id, seed_session_itl_unlock_folders,
    seed_session_local_itg_score_for_id, seed_session_online_itl_self_rank,
    seed_session_online_itl_self_score,
    set_active_profile_for_side_from_config as set_active_profile_for_side,
    set_active_profiles_from_config as set_active_profiles, set_arrowcloud_api_key_for_id,
    set_arrowcloud_api_key_for_side, set_cached_itl_file_for_id, set_default_pad_config,
    set_groovestats_credentials_for_id, set_groovestats_credentials_for_side, should_warn_itl_cmod,
    smx_gif_packs_from_config as smx_gif_packs, sync_known_packs, toggle_favorite,
    toggle_pack_favorite, total_songs_played_for_id, total_songs_played_for_side,
    update_default_profile_for_side_from_config as set_default_profile_for_side,
    update_machine_default_noteskin_from_config as update_machine_default_noteskin,
    upsert_pad_config, write_imported_favorites, write_imported_profile_stats,
    write_itl_file_for_id,
};
pub use crate::update::*;
pub use crate::{
    runtime_active_local_profile_id_for_side as active_local_profile_id_for_side,
    runtime_active_profile_for_side as get_active_profile_for_side, runtime_current_profile as get,
    runtime_fast_profile_switch_from_select_music as fast_profile_switch_from_select_music,
    runtime_footer_fields_for_side as footer_fields_for_side,
    runtime_gameplay_hud_snapshot as gameplay_hud_snapshot,
    runtime_groovestats_api_key_for_side as groovestats_api_key_for_side,
    runtime_known_pack_names_for_local_profile as known_pack_names_for_local_profile,
    runtime_local_profile_id_for_pad as active_local_profile_id_for_pad,
    runtime_pad_light_brightness_for_pad as pad_light_brightness_for_pad,
    runtime_profile_for_side as get_for_side, runtime_profile_has_favorite_for_side as is_favorite,
    runtime_profile_has_favorited_pack_for_side as is_pack_favorite,
    runtime_seed_favorite_for_side as seed_session_favorite,
    runtime_seed_favorited_pack_for_side as seed_session_favorited_pack,
    runtime_session_music_rate as get_session_music_rate,
    runtime_session_play_mode as get_session_play_mode,
    runtime_session_play_style as get_session_play_style,
    runtime_session_player_side as get_session_player_side,
    runtime_session_side_guest as is_session_side_guest,
    runtime_session_side_joined as is_session_side_joined,
    runtime_session_timing_tick_mode as get_session_timing_tick_mode,
    runtime_set_avatar_texture_key_for_side as set_avatar_texture_key_for_side,
    runtime_set_fast_profile_switch_from_select_music as set_fast_profile_switch_from_select_music,
    runtime_set_session_joined as set_session_joined,
    runtime_set_session_music_rate as set_session_music_rate,
    runtime_set_session_play_mode as set_session_play_mode,
    runtime_set_session_play_style as set_session_play_style,
    runtime_set_session_player_side as set_session_player_side,
    runtime_set_session_timing_tick_mode as set_session_timing_tick_mode,
    runtime_take_fast_profile_switch_from_select_music as take_fast_profile_switch_from_select_music,
};
