[package]
name = "deadlib-audio-backend-coreaudio"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0"

[target.'cfg(target_os = "macos")'.dependencies]
coreaudio = { package = "coreaudio-rs", version = "0.14.2" }
deadlib-audio = { path = "../deadlib-audio" }
deadlib-audio-backend-telemetry = { path = "../deadlib-audio-backend-telemetry" }
deadlib-platform = { path = "../deadlib-platform" }
log = "0.4.33"
mach2 = "0.6.0"
objc2-core-audio = "0.3.2"
objc2-core-foundation = "0.3.2"

[lints.clippy]
perf = { level = "warn", priority = -1 }

inline_always = "allow"
