[package]
name = "deadlib-audio-backend-native"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0"

[dependencies]
deadlib-audio = { path = "../deadlib-audio" }
log = "0.4.33"

[features]
pipewire-audio = ["dep:deadlib-audio-backend-pipewire"]

[target.'cfg(windows)'.dependencies]
deadlib-audio-backend-wasapi = { path = "../deadlib-audio-backend-wasapi" }

[target.'cfg(target_os = "freebsd")'.dependencies]
deadlib-audio-backend-freebsd-pcm = { path = "../deadlib-audio-backend-freebsd-pcm" }

[target.'cfg(target_os = "linux")'.dependencies]
deadlib-audio-backend-alsa = { path = "../deadlib-audio-backend-alsa" }
deadlib-audio-backend-jack = { path = "../deadlib-audio-backend-jack" }
deadlib-audio-backend-pipewire = { path = "../deadlib-audio-backend-pipewire", optional = true }
deadlib-audio-backend-pulse = { path = "../deadlib-audio-backend-pulse" }

[target.'cfg(target_os = "macos")'.dependencies]
deadlib-audio-backend-coreaudio = { path = "../deadlib-audio-backend-coreaudio" }

[lints.clippy]
perf = { level = "warn", priority = -1 }

inline_always = "allow"
