# GifPack.ini


# Set the fallback gif pack to any other pack in the "dance" folder.
# When this is not defined, default to "common" fallback.
# Set to "none" for no fallback.
#
#Fallback=""


# Comma-separated role name list that will have no fallback if not
# supplied in this pack.
#
#CanBeEmpty=""


# Comma-separated role name list that will be multiplied by the difficulty
# color based on the chosen theme.
#
# Note: In this specific pack "senpi-basic" we're using the common "results_25.gif"
#       fallback since it's grayscale, but letting it be changed by the difficulty color.
#
MatchColorToDifficulty="results"

# Comma-separated role name list of bpm variants to merge with the "common" pack
# variants.
#
MergeCommonBPMVariants="song_select"

# Comma-separated role name list of bpm variants to merge with the "fallback" pack
# variants. The fallback pack being defined above.
#
#MergeFallbackBPMVariants=""
