[package]
name = "deadsync-noteskin"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0"

[dependencies]
arrayvec = "0.7.8"
bincode = { package = "deadlib-bincode", version = "=2.0.1", path = "../deadlib-bincode" }
hashbrown = "0.17.1"
image = "0.25.10"
log = "0.4.34"
mlua = { version = "0.12.1", features = ["lua54", "vendored"] }
serde = { version = "1.0.229", features = ["derive"] }
smallvec = "1.16.0"
twox-hash = "2.1.4"

[lints.clippy]
perf = { level = "warn", priority = -1 }

inline_always = "allow"
