name: release-all

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (example: v0.2.22)"
        required: true
        type: string

permissions:
  contents: write

jobs:
  release-linux:
    uses: ./.github/workflows/release-linux.yml
    with:
      tag: ${{ inputs.tag }}
      arch: all
    secrets: inherit

  release-macos:
    uses: ./.github/workflows/release-macos.yml
    with:
      tag: ${{ inputs.tag }}
      arch: all
    secrets: inherit

  release-windows:
    uses: ./.github/workflows/release-windows.yml
    with:
      tag: ${{ inputs.tag }}
    secrets: inherit
